import type {
  ActionDefinition,
  CharacterDefinition,
  CombatContent,
} from "../combat/types";

export const actions = [
  {
    id: "action.mara-vex.invoice-breaker",
    name: "Invoice Breaker",
    description: "A quick single-target hit. No forms required.",
    position: "1",
    chargeMs: 0,
    effects: [{ kind: "damage", target: "activeEnemy", power: 18 }],
    presentationId: "presentation.mara.quick",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.mara-vex.red-tape",
    name: "Red Tape",
    description: "Charge, strike, and probably stun the active enemy.",
    position: "2",
    chargeMs: 650,
    effects: [
      { kind: "damage", target: "activeEnemy", power: 16 },
      {
        kind: "stun",
        target: "activeEnemy",
        durationMs: 950,
        chance: 0.72,
      },
    ],
    presentationId: "presentation.mara.control",
    audioId: "sfx.action.control",
  },
  {
    id: "action.mara-vex.hostile-takeover",
    name: "Hostile Takeover",
    description: "A three-hit finisher that leaves Mara more dangerous.",
    position: "3H",
    chargeMs: 1_150,
    effects: [
      {
        kind: "damage",
        target: "activeEnemy",
        power: 12,
        hits: 3,
      },
      {
        kind: "modifyAttack",
        target: "self",
        magnitude: 0.16,
        durationMs: 6_000,
      },
    ],
    presentationId: "presentation.mara.finisher",
    audioId: "sfx.action.finisher",
  },
  {
    id: "action.knuckle-tax.late-fee",
    name: "Late Fee",
    description: "A cheap hit that somehow costs you more.",
    position: "1",
    chargeMs: 0,
    effects: [{ kind: "damage", target: "activeEnemy", power: 17 }],
    presentationId: "presentation.knuckle.quick",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.knuckle-tax.audit-wall",
    name: "Audit Wall",
    description: "Gain a shield and claw back Charge.",
    position: "2L",
    chargeMs: 0,
    effects: [
      {
        kind: "shield",
        target: "self",
        amount: 11,
        durationMs: 5_000,
      },
      { kind: "bar", target: "allies", amount: 10 },
    ],
    presentationId: "presentation.knuckle.guard",
    audioId: "sfx.action.guard",
  },
  {
    id: "action.knuckle-tax.asset-freeze",
    name: "Asset Freeze",
    description: "A slow charge that hits hard and locks the target.",
    position: "3",
    chargeMs: 1_350,
    effects: [
      { kind: "damage", target: "activeEnemy", power: 31 },
      {
        kind: "stun",
        target: "activeEnemy",
        durationMs: 1_150,
        chance: 0.8,
      },
    ],
    presentationId: "presentation.knuckle.finisher",
    audioId: "sfx.action.finisher",
  },
  {
    id: "action.zipwire.jump-start",
    name: "Jump Start",
    description: "A fast hit that adds Charge back to the team.",
    position: "1H",
    chargeMs: 0,
    effects: [
      { kind: "damage", target: "activeEnemy", power: 15 },
      { kind: "bar", target: "allies", amount: 8 },
    ],
    presentationId: "presentation.generic.quick",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.zipwire.brownout",
    name: "Brownout",
    description: "Damage the active enemy and drain its Charge.",
    position: "2",
    chargeMs: 450,
    effects: [
      { kind: "damage", target: "activeEnemy", power: 18 },
      { kind: "bar", target: "enemies", amount: -15 },
    ],
    presentationId: "presentation.generic.control",
    audioId: "sfx.action.control",
  },
  {
    id: "action.zipwire.full-tilt",
    name: "Full Tilt",
    description: "Hit the whole enemy Lineup.",
    position: "3",
    chargeMs: 900,
    effects: [{ kind: "damage", target: "allEnemies", power: 13 }],
    presentationId: "presentation.generic.finisher",
    audioId: "sfx.action.finisher",
  },
  {
    id: "action.velvet-hex.soft-landing",
    name: "Soft Landing",
    description: "Restore health to the active Relic.",
    position: "1H",
    chargeMs: 0,
    effects: [{ kind: "heal", target: "activeAlly", power: 19 }],
    presentationId: "presentation.generic.heal",
    audioId: "sfx.action.heal",
  },
  {
    id: "action.velvet-hex.bad-omen",
    name: "Bad Omen",
    description: "Lower the active enemy's defence.",
    position: "2",
    chargeMs: 500,
    effects: [
      {
        kind: "modifyDefence",
        target: "activeEnemy",
        magnitude: 0.28,
        durationMs: 6_000,
      },
    ],
    presentationId: "presentation.generic.control",
    audioId: "sfx.action.control",
  },
  {
    id: "action.velvet-hex.curtain-call",
    name: "Curtain Call",
    description: "Heal every living ally and clear negative effects.",
    position: "3",
    chargeMs: 1_050,
    effects: [
      { kind: "heal", target: "allAllies", power: 14 },
      { kind: "cleanse", target: "allAllies" },
    ],
    presentationId: "presentation.generic.heal",
    audioId: "sfx.action.heal",
  },
  {
    id: "action.gutter-grin.sucker-sticker",
    name: "Sucker Sticker",
    description: "A nimble quick hit.",
    position: "1",
    chargeMs: 0,
    effects: [{ kind: "damage", target: "activeEnemy", power: 16 }],
    presentationId: "presentation.generic.quick",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.gutter-grin.false-bottom",
    name: "False Bottom",
    description: "Gain a temporary shield.",
    position: "2",
    chargeMs: 250,
    effects: [
      {
        kind: "shield",
        target: "self",
        amount: 16,
        durationMs: 4_500,
      },
    ],
    presentationId: "presentation.generic.guard",
    audioId: "sfx.action.guard",
  },
  {
    id: "action.gutter-grin.last-laugh",
    name: "Last Laugh",
    description: "A heavy hit that weakens enemy attack.",
    position: "3",
    chargeMs: 850,
    effects: [
      { kind: "damage", target: "activeEnemy", power: 29 },
      {
        kind: "modifyAttack",
        target: "activeEnemy",
        magnitude: -0.2,
        durationMs: 5_000,
      },
    ],
    presentationId: "presentation.generic.finisher",
    audioId: "sfx.action.finisher",
  },
  {
    id: "action.scrapjack.bin-kick",
    name: "Bin Kick",
    description: "Fast, rude, effective.",
    position: "1",
    chargeMs: 0,
    effects: [{ kind: "damage", target: "activeEnemy", power: 18 }],
    presentationId: "presentation.generic.quick",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.scrapjack.loose-screws",
    name: "Loose Screws",
    description: "Raise attack for a short burst.",
    position: "2",
    chargeMs: 300,
    effects: [
      {
        kind: "modifyAttack",
        target: "self",
        magnitude: 0.26,
        durationMs: 5_500,
      },
    ],
    presentationId: "presentation.generic.control",
    audioId: "sfx.action.control",
  },
  {
    id: "action.scrapjack.hard-rubbish",
    name: "Hard Rubbish",
    description: "Damage every enemy Relic.",
    position: "3H",
    chargeMs: 1_100,
    effects: [{ kind: "damage", target: "allEnemies", power: 15 }],
    presentationId: "presentation.generic.finisher",
    audioId: "sfx.action.finisher",
  },
] satisfies ActionDefinition[];

export const characters = [
  {
    id: "character.mara-vex",
    name: "Mara Vex",
    lore: "A bootleg bruiser printed after midnight, Mara treats every cease-and-desist as an invitation to make another copy.",
    classId: "impact",
    factionId: "faction.free-shelf",
    level: 7,
    baseStats: { health: 112, power: 6, evasion: 3, fortune: 5, tempo: 5 },
    actionIds: [
      "action.mara-vex.invoice-breaker",
      "action.mara-vex.red-tape",
      "action.mara-vex.hostile-takeover",
    ],
    portraitAssetId: "image.mara-vex.canonical",
    idleAssetIds: ["image.mara-vex.idle.a", "image.mara-vex.idle.b"],
    musicId: "music.red-thread",
  },
  {
    id: "character.knuckle-tax",
    name: "Knuckle Tax",
    lore: "The Ledger's collection agent arrives with a locked briefcase, an itemised threat, and no concept of store credit.",
    classId: "guard",
    factionId: "faction.the-ledger",
    level: 6,
    baseStats: { health: 126, power: 5, evasion: 1, fortune: 2, tempo: 3 },
    actionIds: [
      "action.knuckle-tax.late-fee",
      "action.knuckle-tax.audit-wall",
      "action.knuckle-tax.asset-freeze",
    ],
    portraitAssetId: "image.knuckle-tax.canonical",
    idleAssetIds: ["image.knuckle-tax.idle.a", "image.knuckle-tax.idle.b"],
    musicId: "music.no-control",
  },
  {
    id: "character.zipwire",
    name: "Zipwire",
    lore: "A live wire in discount packaging, Zipwire turns bad connections and worse timing into impossible speed.",
    classId: "circuit",
    factionId: "faction.free-shelf",
    level: 6,
    baseStats: { health: 92, power: 4, evasion: 6, fortune: 4, tempo: 9 },
    actionIds: [
      "action.zipwire.jump-start",
      "action.zipwire.brownout",
      "action.zipwire.full-tilt",
    ],
    portraitAssetId: "image.zipwire.canonical",
    idleAssetIds: ["image.zipwire.idle.a", "image.zipwire.idle.b"],
    musicId: "music.soft-static-halo",
  },
  {
    id: "character.velvet-hex",
    name: "Velvet Hex",
    lore: "House Stock's soft-spoken omen can mend a cracked Lineup or make an opponent's luck expire without notice.",
    classId: "hex",
    factionId: "faction.house-stock",
    level: 6,
    baseStats: { health: 98, power: 3, evasion: 4, fortune: 7, tempo: 5 },
    actionIds: [
      "action.velvet-hex.soft-landing",
      "action.velvet-hex.bad-omen",
      "action.velvet-hex.curtain-call",
    ],
    portraitAssetId: "image.velvet-hex.canonical",
    idleAssetIds: ["image.velvet-hex.idle.a", "image.velvet-hex.idle.b"],
    musicId: "music.mirrors",
  },
  {
    id: "character.gutter-grin",
    name: "Gutter Grin",
    lore: "Found face-down beneath a market stall, this smiling fake wins fights by ensuring the obvious move is never the real one.",
    classId: "guile",
    factionId: "faction.house-stock",
    level: 5,
    baseStats: { health: 94, power: 5, evasion: 8, fortune: 6, tempo: 6 },
    actionIds: [
      "action.gutter-grin.sucker-sticker",
      "action.gutter-grin.false-bottom",
      "action.gutter-grin.last-laugh",
    ],
    portraitAssetId: "image.gutter-grin.canonical",
    idleAssetIds: ["image.gutter-grin.idle.a", "image.gutter-grin.idle.b"],
    musicId: "music.obsessed",
  },
  {
    id: "character.scrapjack",
    name: "Scrapjack",
    lore: "Built from recalled parts and pure grievance, Scrapjack considers every bin a parts catalogue and every arena a workshop.",
    classId: "feral",
    factionId: "faction.the-ledger",
    level: 5,
    baseStats: { health: 108, power: 7, evasion: 2, fortune: 3, tempo: 4 },
    actionIds: [
      "action.scrapjack.bin-kick",
      "action.scrapjack.loose-screws",
      "action.scrapjack.hard-rubbish",
    ],
    portraitAssetId: "image.scrapjack.canonical",
    idleAssetIds: ["image.scrapjack.idle.a", "image.scrapjack.idle.b"],
    musicId: "music.weather-outside",
  },
] satisfies CharacterDefinition[];

export const combatContent: CombatContent = {
  actions: Object.fromEntries(actions.map((action) => [action.id, action])),
  characters: Object.fromEntries(
    characters.map((character) => [character.id, character]),
  ),
};

export const storyNodes = [
  {
    id: "story.first-run.00",
    index: "00",
    type: "dialogue",
    title: "Wet Ink",
    summary: "The Ledger arrives before the posters are dry.",
    next: "story.first-run.01",
  },
  {
    id: "story.first-run.01",
    index: "01",
    type: "reward",
    title: "Shelf Space",
    summary: "Mara Vex joins your Lineup.",
    next: "story.first-run.02",
  },
  {
    id: "story.first-run.02",
    index: "02",
    type: "battle",
    title: "Tax Due",
    summary: "Knuckle Tax would like a word and all of your Stamps.",
    next: "story.first-run.03",
  },
  {
    id: "story.first-run.03",
    index: "03",
    type: "store",
    title: "Backroom Counter",
    summary: "Rotating stock, questionable provenance.",
    next: "story.first-run.04",
  },
  {
    id: "story.first-run.04",
    index: "04",
    type: "mission",
    title: "Read the Fine Print",
    summary: "Three new missions hit the board.",
    next: "story.first-run.05",
  },
  {
    id: "story.first-run.05",
    index: "05",
    type: "battle",
    title: "Qualifier Stamp",
    summary: "Bring more than one Relic.",
    next: "story.first-run.06",
  },
  {
    id: "story.first-run.06",
    index: "06",
    type: "tournament",
    title: "The Cheap Seats Cup",
    summary: "Three rounds. One Case. No refunds.",
    next: "story.first-run.07",
  },
  {
    id: "story.first-run.07",
    index: "07",
    type: "ending",
    title: "Officially Unofficial",
    summary: "The first print run survives.",
    next: null,
  },
] as const;

export const missions = [
  {
    id: "mission.fresh-ink",
    name: "Fresh Ink",
    description: "Own two distinct Relics.",
    target: 2,
    rewardStamps: 90,
  },
  {
    id: "mission.invoice-denied",
    name: "Invoice Denied",
    description: "Defeat Knuckle Tax.",
    target: 1,
    rewardStamps: 120,
  },
  {
    id: "mission.print-it-personal",
    name: "Print It Personal",
    description: "Return and defeat an opponent who beat you.",
    target: 1,
    rewardStamps: 180,
  },
] as const;
