import type { ActionDefinition, CharacterDefinition } from "../combat/types";

export const launchActions = [
  {
    id: "action.tux.ping",
    name: "Ping",
    description: "A quick packet that lands a hit and returns team Charge.",
    category: "strip",
    position: "1H",
    chargeMs: 0,
    effects: [
      { kind: "damage", target: "activeEnemy", power: 15 },
      { kind: "bar", target: "allies", amount: 8, requiresHit: true },
    ],
    presentationId: "presentation.tux.ping",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.tux.root-access",
    name: "Root Access",
    description: "Damage the target, drain its Charge, and slow its Strip.",
    category: "strip",
    position: "2",
    chargeMs: 450,
    interruptionPolicy: "spend",
    effects: [
      { kind: "damage", target: "activeEnemy", power: 18 },
      {
        kind: "bar",
        target: "enemies",
        amount: -15,
        requiresHit: true,
      },
      {
        kind: "modifyChargeRate",
        target: "enemies",
        multiplier: 0.72,
        durationMs: 3_000,
        requiresHit: true,
      },
    ],
    presentationId: "presentation.tux.root-access",
    audioId: "sfx.action.control",
  },
  {
    id: "action.tux.kernel-panic",
    name: "Kernel Panic",
    description: "Crash through the whole opposing Lineup.",
    category: "teamAttack",
    position: "3",
    chargeMs: 900,
    interruptionPolicy: "spend",
    effects: [{ kind: "damage", target: "allEnemies", power: 13 }],
    presentationId: "presentation.tux.kernel-panic",
    audioId: "sfx.action.finisher",
  },
  {
    id: "action.humpty.egg-on-your-face",
    name: "Egg on Your Face",
    description:
      "A quick hit that sharpens Evasion; the next clean dodge snaps back.",
    category: "special",
    position: "1",
    chargeMs: 0,
    effects: [
      { kind: "damage", target: "activeEnemy", power: 16 },
      {
        kind: "modifyEvasion",
        target: "self",
        magnitude: 4,
        durationMs: 3_000,
        requiresHit: true,
      },
      {
        kind: "counterOnDodge",
        target: "self",
        power: 10,
        durationMs: 3_000,
        uses: 1,
        requiresHit: true,
      },
    ],
    presentationId: "presentation.humpty.egg-on-your-face",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.humpty.shell-game",
    name: "Shell Game",
    description: "Hide behind a shell that throws part of each hit back.",
    category: "support",
    position: "2",
    chargeMs: 250,
    interruptionPolicy: "spend",
    effects: [
      {
        kind: "shield",
        target: "self",
        amount: 16,
        durationMs: 4_500,
      },
      {
        kind: "reflectDamage",
        target: "self",
        ratio: 0.35,
        durationMs: 4_500,
      },
    ],
    presentationId: "presentation.humpty.shell-game",
    audioId: "sfx.action.guard",
  },
  {
    id: "action.humpty.great-fall",
    name: "Great Fall",
    description: "Come down hard, leave a mess, and rattle the target.",
    category: "stun",
    position: "3",
    chargeMs: 850,
    interruptionPolicy: "spend",
    effects: [
      { kind: "damage", target: "activeEnemy", power: 27 },
      {
        kind: "stun",
        target: "activeEnemy",
        durationMs: 900,
        chance: 0.68,
        requiresHit: true,
      },
      {
        kind: "damageOverTime",
        target: "activeEnemy",
        power: 3,
        durationMs: 3_000,
        intervalMs: 1_000,
        requiresHit: true,
      },
    ],
    presentationId: "presentation.humpty.great-fall",
    audioId: "sfx.action.finisher",
  },
  {
    id: "action.moses.staff-tap",
    name: "Staff Tap",
    description: "Restore health now, then mend the active ally over time.",
    category: "support",
    position: "1H",
    chargeMs: 0,
    effects: [
      { kind: "heal", target: "activeAlly", power: 14 },
      {
        kind: "healOverTime",
        target: "activeAlly",
        power: 3,
        durationMs: 3_000,
        intervalMs: 1_000,
      },
    ],
    presentationId: "presentation.moses.staff-tap",
    audioId: "sfx.action.heal",
  },
  {
    id: "action.moses.part-the-strip",
    name: "Part the Strip",
    description: "Nick the active enemy and leave its defence divided.",
    category: "special",
    position: "2",
    chargeMs: 500,
    interruptionPolicy: "spend",
    effects: [
      { kind: "damage", target: "activeEnemy", power: 8 },
      {
        kind: "modifyDefence",
        target: "activeEnemy",
        magnitude: 0.28,
        durationMs: 6_000,
        requiresHit: true,
      },
    ],
    presentationId: "presentation.moses.part-the-strip",
    audioId: "sfx.action.control",
  },
  {
    id: "action.moses.safe-passage",
    name: "Safe Passage",
    description: "Mend and cleanse every living ally.",
    category: "teamSupport",
    position: "3",
    chargeMs: 1_050,
    interruptionPolicy: "spend",
    effects: [
      { kind: "heal", target: "allAllies", power: 14 },
      { kind: "cleanse", target: "allAllies" },
    ],
    presentationId: "presentation.moses.safe-passage",
    audioId: "sfx.action.heal",
  },
  {
    id: "action.viking.axe-first",
    name: "Axe First",
    description:
      "Throw a returning axe for dependable damage. Tier 1 makes it undodgeable.",
    category: "attack",
    position: "2L",
    chargeMs: 0,
    effects: [{ kind: "damage", target: "activeEnemy", power: 20 }],
    tierProperties: {
      gold: { undodgeable: true },
    },
    presentationId: "presentation.viking.axe-first",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.viking.shield-bash",
    name: "Battle Boast",
    description:
      "Bank +28% Power for Viking's next attack. Use it again to stack; the attack spends every stack.",
    category: "support",
    position: "1L",
    chargeMs: 0,
    effects: [
      {
        kind: "empowerNextMove",
        target: "self",
        magnitude: 0.4,
      },
    ],
    presentationId: "presentation.viking.shield-bash",
    audioId: "sfx.action.guard",
  },
  {
    id: "action.viking.berserker-oath",
    name: "Berserker Oath",
    description:
      "Bring the axe down in Viking's strongest default hit. After it lands, it has a 72% chance to stun.",
    category: "attack",
    position: "3L",
    chargeMs: 700,
    interruptionPolicy: "spend",
    effects: [
      {
        kind: "damage",
        target: "activeEnemy",
        power: 29,
      },
      {
        kind: "stun",
        target: "activeEnemy",
        durationMs: 650,
        chance: 0.72,
        requiresHit: true,
      },
    ],
    presentationId: "presentation.viking.berserker-oath",
    audioId: "sfx.action.finisher",
  },
  {
    id: "action.ned-kelly.warning-shot",
    name: "Warning Shot",
    description: "A precise shot that cannot be dodged.",
    category: "attack",
    position: "1",
    chargeMs: 0,
    effects: [
      {
        kind: "damage",
        target: "activeEnemy",
        power: 17,
        undodgeable: true,
      },
    ],
    presentationId: "presentation.ned-kelly.warning-shot",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.ned-kelly.iron-outlaw",
    name: "Iron Outlaw",
    description: "Brace behind plate armour and return part of every hit.",
    category: "support",
    position: "2L",
    chargeMs: 0,
    effects: [
      { kind: "shield", target: "self", amount: 15, durationMs: 5_000 },
      { kind: "bar", target: "allies", amount: 10 },
      {
        kind: "reflectDamage",
        target: "self",
        ratio: 0.25,
        durationMs: 5_000,
      },
    ],
    presentationId: "presentation.ned-kelly.iron-outlaw",
    audioId: "sfx.action.guard",
  },
  {
    id: "action.ned-kelly.last-stand",
    name: "Last Stand",
    description: "A shield-piercing shot that briefly blocks switching.",
    category: "stun",
    position: "3",
    chargeMs: 1_100,
    interruptionPolicy: "spend",
    effects: [
      {
        kind: "damage",
        target: "activeEnemy",
        power: 31,
        shieldPiercing: true,
      },
      {
        kind: "switchLock",
        target: "activeEnemy",
        durationMs: 3_000,
        requiresHit: true,
      },
      {
        kind: "stun",
        target: "activeEnemy",
        durationMs: 1_150,
        chance: 0.8,
        requiresHit: true,
      },
    ],
    presentationId: "presentation.ned-kelly.last-stand",
    audioId: "sfx.action.finisher",
  },
  {
    id: "action.grim-reaper.cold-touch",
    name: "Cold Touch",
    description: "A quick cut that weakens the target's Power.",
    category: "special",
    position: "1",
    chargeMs: 0,
    effects: [
      { kind: "damage", target: "activeEnemy", power: 16 },
      {
        kind: "modifyAttack",
        target: "activeEnemy",
        magnitude: -0.14,
        durationMs: 4_000,
        requiresHit: true,
      },
    ],
    presentationId: "presentation.grim-reaper.cold-touch",
    audioId: "sfx.action.quick",
  },
  {
    id: "action.grim-reaper.deaths-shadow",
    name: "Death's Shadow",
    description: "Let the shadow grow and raise Power for a short burst.",
    category: "support",
    position: "2",
    chargeMs: 300,
    interruptionPolicy: "spend",
    effects: [
      {
        kind: "modifyAttack",
        target: "self",
        magnitude: 0.26,
        durationMs: 5_500,
      },
    ],
    presentationId: "presentation.grim-reaper.deaths-shadow",
    audioId: "sfx.action.control",
  },
  {
    id: "action.grim-reaper.final-harvest",
    name: "Final Harvest",
    description: "Reap the whole enemy Lineup and recover health from the hit.",
    category: "teamAttack",
    position: "3H",
    chargeMs: 1_100,
    interruptionPolicy: "spend",
    effects: [
      {
        kind: "damage",
        target: "allEnemies",
        power: 15,
        lifeStealRatio: 0.3,
      },
    ],
    presentationId: "presentation.grim-reaper.final-harvest",
    audioId: "sfx.action.finisher",
  },
] satisfies ActionDefinition[];

export const launchCharacters = [
  {
    id: "character.tux",
    name: "Tux",
    lore: "A cheerful open-source penguin who treats every locked system as a polite invitation to collaborate.",
    typeId: "tech",
    traitIds: ["icon"],
    level: 6,
    baseStats: { health: 92, power: 4, evasion: 6, fortune: 4, tempo: 9 },
    actionIds: [
      "action.tux.ping",
      "action.tux.root-access",
      "action.tux.kernel-panic",
    ],
    portraitAssetId: "image.tux.canonical",
    idleAssetIds: ["image.tux.idle.a", "image.tux.idle.b"],
    reactionAssetId: "image.tux.reactions",
    musicId: "music.character.tux",
  },
  {
    id: "character.humpty",
    name: "Humpty Dumpty",
    lore: "The famous wall enthusiast insists the fall was tactical and the king's horses simply ignored the recovery plan.",
    typeId: "oddball",
    traitIds: ["icon"],
    level: 5,
    baseStats: { health: 94, power: 5, evasion: 8, fortune: 6, tempo: 6 },
    actionIds: [
      "action.humpty.egg-on-your-face",
      "action.humpty.shell-game",
      "action.humpty.great-fall",
    ],
    portraitAssetId: "image.humpty.canonical",
    idleAssetIds: ["image.humpty.idle.a", "image.humpty.idle.b"],
    reactionAssetId: "image.humpty.reactions",
    musicId: "music.character.humpty",
  },
  {
    id: "character.moses",
    name: "Moses",
    lore: "A miracle-working leader carrying a staff, a serious sense of purpose, and no patience for obstructed routes.",
    typeId: "arcane",
    traitIds: ["hero", "mythic"],
    level: 6,
    baseStats: { health: 98, power: 3, evasion: 4, fortune: 7, tempo: 5 },
    actionIds: [
      "action.moses.staff-tap",
      "action.moses.part-the-strip",
      "action.moses.safe-passage",
    ],
    portraitAssetId: "image.moses.canonical",
    idleAssetIds: ["image.moses.idle.a", "image.moses.idle.b"],
    reactionAssetId: "image.moses.reactions",
    musicId: "music.character.moses",
  },
  {
    id: "character.viking",
    name: "Viking",
    lore: "A saga-era raider who heard there would be prizes, misunderstood every other detail, and arrived battle-ready.",
    typeId: "brawler",
    traitIds: ["historic"],
    level: 7,
    baseStats: { health: 112, power: 6, evasion: 3, fortune: 5, tempo: 5 },
    actionIds: [
      "action.viking.shield-bash",
      "action.viking.axe-first",
      "action.viking.berserker-oath",
    ],
    portraitAssetId: "image.viking.canonical",
    idleAssetIds: ["image.viking.idle.a", "image.viking.idle.b"],
    reactionAssetId: "image.viking.reactions",
    musicId: "music.character.viking",
  },
  {
    id: "character.ned-kelly",
    name: "Ned Kelly",
    lore: "The armoured Australian outlaw enters the bracket under protest and refuses to remove the helmet for identification.",
    typeId: "sharpshooter",
    traitIds: ["hero", "historic"],
    level: 6,
    baseStats: { health: 108, power: 6, evasion: 4, fortune: 6, tempo: 4 },
    actionIds: [
      "action.ned-kelly.warning-shot",
      "action.ned-kelly.iron-outlaw",
      "action.ned-kelly.last-stand",
    ],
    portraitAssetId: "image.ned-kelly.canonical",
    idleAssetIds: ["image.ned-kelly.idle.a", "image.ned-kelly.idle.b"],
    reactionAssetId: "image.ned-kelly.reactions",
    musicId: "music.character.ned-kelly",
  },
  {
    id: "character.grim-reaper",
    name: "Grim Reaper",
    lore: "The embodiment of death has joined a light entertainment tournament and remains baffled by the waiver.",
    typeId: "beast",
    traitIds: ["monster", "mythic"],
    level: 5,
    baseStats: { health: 108, power: 7, evasion: 2, fortune: 3, tempo: 4 },
    actionIds: [
      "action.grim-reaper.cold-touch",
      "action.grim-reaper.deaths-shadow",
      "action.grim-reaper.final-harvest",
    ],
    portraitAssetId: "image.grim-reaper.canonical",
    idleAssetIds: ["image.grim-reaper.idle.a", "image.grim-reaper.idle.b"],
    reactionAssetId: "image.grim-reaper.reactions",
    musicId: "music.character.grim-reaper",
  },
] satisfies CharacterDefinition[];
